version: Wesnoth-VS2013-{branch}-{build}
clone_folder: C:\projects\wesnoth
image: Visual Studio 2013
configuration:
 - Release
 - Debug
platform: win32
skip_branch_with_pr: true
shallow_clone: true
before_build:
  - cd ..
  - ps: wget https://github.com/aquileia/external/archive/VC12.zip -O VC12.zip
  - 7z x VC12.ZIP
  - ren external-VC12 external
  - cd wesnoth
  - set PATH=C:\projects\external\dll;%PATH%

notifications:
  - provider: Webhook
    url: http://ai0867.net:9999/
    headers:
      User-Agent: WesnothAppveyor/1.0
      Authorization: TODO
      Configuration: "{configuration_name}"
      Commit: "{commitId}"
      Message: "{message}"
      Url: "{build_url}"
      Status: "{status}"
    on_build_success: true
    on_build_failure: true
